# Generated by Django 5.2.2 on 2025-06-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoBTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('preco_previsto', models.FloatField()),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
    ]
