# Generated by Django 5.2.2 on 2025-06-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_btc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previsaobtc',
            name='modelo',
        ),
        migrations.AlterField(
            model_name='previsaobtc',
            name='data',
            field=models.DateField(unique=True),
        ),
    ]
